### ISSUE TITLE
Test Case Documentation

### ISSUE THREAD

**Issue by zxnlee** [zxnlee/ETIAssignment#1]
QA Team to work on the test case documentation for the following features:
1. Display main menu
2. Read and load maze from file
3. View maze
4. Play maze game
5. Configure current maze
Details of each feature has been attached in [Requirements.pdf](https://github.com/zxnlee/ETIAssignment/files/4112167/Requirements.pdf)

Deadline on 27th January 2020.

**Comment by geraldngkj98** [comment]
@zxnlee Please help to check and update the test cases. Thank you.

**Comment by zxnlee** [comment]
@geraldngkj98 Updated

**Comment by zxnlee** [comment]
all test cases done and justified (if applicable)
issue will be closed
