### ISSUE TITLE
Test case scripts

### ISSUE THREAD

**Issue by zxnlee** [zxnlee/ETIAssignment#2]
@geraldngkj98, QA Team to work on the test case scripts for the features and documentation from issue #1.

Deadline: 2nd February 2020

**Comment by zxnlee** [comment]
@geraldngkj98 @SandyK95 #1 test case documentation has been updated, please proceed with the test case scripts

**Comment by geraldngkj98** [comment]
#2 @SandyK95 Please work on test scripts for 1.0 to 4.0.

**Comment by SandyK95** [comment]
@geraldngkj98 @zxnlee Committed test scripts for 1.0 to 3.0

**Comment by SandyK95** [comment]
@geraldngkj98 @zxnlee Committed test scripts for 4.0

**Comment by geraldngkj98** [comment]
@zxnlee Please work on test 5.0 thanks!

**Comment by zxnlee** [comment]
@geraldngkj98 Committed test scripts for 5.0

**Comment by geraldngkj98** [comment]
@zxnlee Please work on tests 6.0 to 8.0. I will be completing the rest of the tests.

**Comment by zxnlee** [comment]
@geraldngkj98 will get the play maze test scripts (6.0-8.0) done by tomorrow.
@dianizzati @kkwwnnpp Take note.

**Comment by zxnlee** [comment]
@geraldngkj98 committed test scripts for 6.0-8.0

**Comment by geraldngkj98** [comment]
@zxnlee Please extend the timeline for the rest of the cases. Will try to complete by 3rd February.

**Comment by zxnlee** [comment]
@geraldngkj98 ok. 
@dianizzati please note. tentative deadline for configure maze test cases have been shifted to 3rd feb. please extend the deadline for the configure maze feature as well

**Comment by dianizzati** [comment]
Noted.

**Comment by geraldngkj98** [comment]
@zxnlee committed test scripts for the configure maze feature

**Comment by zxnlee** [comment]
all test scripts tested and working
issue will be closed
@geraldngkj98
