### ISSUE TITLE
Development of "Display main menu"

### ISSUE THREAD

**Issue by zxnlee** [zxnlee/ETIAssignment#3]
Development team to work on the development of "display main menu".
Refer to 
![image](https://user-images.githubusercontent.com/56616436/73123377-778e9c80-3fca-11ea-970c-270e5d8837b9.png)

Also refer to issue #1 and #2 for more test cases.

**Comment by zxnlee** [comment]
@dianizzati test scripts 1.0 to 3.0 for the "Display main menu" feature has been committed by @SandyK95. Please develop this feature

**Comment by dianizzati** [comment]
@zxnlee @geraldngkj98 Done with development for this feature.

**Comment by zxnlee** [comment]
@geraldngkj98 Please assign for testing

**Comment by geraldngkj98** [comment]
@SandyK95 Please start the testing for this feature.

**Comment by SandyK95** [comment]
@zxnlee @geraldngkj98 @dianizzati  Done with testing, the three test cases pass.
![test_outputs](https://user-images.githubusercontent.com/32905878/73361363-c9436980-42df-11ea-8526-2bccf38e45a4.JPG)

**Comment by dianizzati** [comment]
Unit Tests:
Display Menu:
<img width="603" alt="Screenshot 2020-02-02 at 12 44 06 PM" src="https://user-images.githubusercontent.com/56821508/73603184-2a0dc300-45ba-11ea-9b40-ca2387a8151d.png">

If the user enters valid option from the menu list:
<img width="536" alt="Screenshot 2020-02-02 at 12 48 37 PM" src="https://user-images.githubusercontent.com/56821508/73603199-7fe26b00-45ba-11ea-8ec7-8859113e8106.png">

If the user enters invalid option, that is not in the menu list:
<img width="505" alt="Screenshot 2020-02-02 at 12 48 58 PM" src="https://user-images.githubusercontent.com/56821508/73603201-8cff5a00-45ba-11ea-9e36-190a31b918b8.png">

When the user chooses to exit or enter '0':
<img width="404" alt="Screenshot 2020-02-02 at 12 49 10 PM" src="https://user-images.githubusercontent.com/56821508/73603220-c2a44300-45ba-11ea-96d3-b7a6ad2a6e18.png">

**Comment by dianizzati** [comment]
Display Menu Unit Test Cases Documentation:
[Display Menu Unit Test Case.docx](https://github.com/zxnlee/ETIAssignment/files/4154698/Display.Menu.Unit.Test.Case.docx)

**Comment by zxnlee** [comment]
feature completed and testing passed.
issue will be closed
@dianizzati @geraldngkj98
