### ISSUE TITLE
Development of "Read and load maze from file"

### ISSUE THREAD

**Issue by zxnlee** [zxnlee/ETIAssignment#4]
Development team to work on the development of "Read and load maze from file". 
Details on requirement:
![image](https://user-images.githubusercontent.com/56616436/73123439-ef5cc700-3fca-11ea-97d9-2f02f1448394.png)

Also refer to #1 and #2 for test cases.

**Comment by zxnlee** [comment]
@dianizzati test scripts 4.0 for the "Read and load maze from file" feature has been committed by @SandyK95. Please develop this feature

```@geraldngkj98 @zxnlee Committed test scripts for 4.0```

_Originally posted by @SandyK95 in https://github.com/zxnlee/ETIAssignment/issues/2#issuecomment-579762069_

**Comment by dianizzati** [comment]
@geraldngkj98  @zxnlee Done with development for this feature.

**Comment by zxnlee** [comment]
@geraldngkj98 please assign for testing

**Comment by geraldngkj98** [comment]
@SandyK95 Please do testing on this feature.

**Comment by SandyK95** [comment]
@geraldngkj98 @zxnlee @dianizzati Testing passed.
![test_outputs](https://user-images.githubusercontent.com/32905878/73460771-011be100-43b4-11ea-9a75-0d296a417b40.JPG)

**Comment by dianizzati** [comment]
Unit Tests:
When the user chooses the option 1 to Read and load maze from file:
<img width="390" alt="Screenshot 2020-02-02 at 12 53 54 PM" src="https://user-images.githubusercontent.com/56821508/73603337-1f542d80-45bc-11ea-9951-eda69ce61693.png">

User enters the file name they want to read & load:
<img width="398" alt="Screenshot 2020-02-02 at 12 54 13 PM" src="https://user-images.githubusercontent.com/56821508/73603347-3d219280-45bc-11ea-93cf-c9c8cb9f0b82.png">

To check if user can read and load other files (other than maze.csv):
<img width="571" alt="Screenshot 2020-02-02 at 12 58 53 PM" src="https://user-images.githubusercontent.com/56821508/73603355-62160580-45bc-11ea-8744-e9df91491989.png">

If the user enters a file name that is not existing in the path:
<img width="473" alt="Screenshot 2020-02-02 at 12 54 41 PM" src="https://user-images.githubusercontent.com/56821508/73603370-85d94b80-45bc-11ea-9792-64b87c9d1087.png">

**Comment by dianizzati** [comment]
Read & Load maze from file Unit Test Cases Documentation:
[Read & Load Maze from File Unit Test.docx](https://github.com/zxnlee/ETIAssignment/files/4154821/Read.Load.Maze.from.File.Unit.Test.docx)

**Comment by zxnlee** [comment]
feature completed and testing passed.
issue will be closed
@dianizzati @geraldngkj98
