### ISSUE TITLE
Development of "View Maze"

### ISSUE THREAD

**Issue by zxnlee** [zxnlee/ETIAssignment#5]
Development team to work on the feature "View Maze"
Details on requirement:
![image](https://user-images.githubusercontent.com/56616436/73123454-11eee000-3fcb-11ea-889f-d21662c4ccc8.png)

Also refer to #1 and #2 for test cases.

**Comment by zxnlee** [comment]
@dianizzati @geraldngkj98 Done with development for this feature

**Comment by zxnlee** [comment]
@geraldngkj98 please assign for testing

**Comment by geraldngkj98** [comment]
@SandyK95 Please start the testing on this feature.

**Comment by SandyK95** [comment]
@zxnlee @geraldngkj98 Testing passed
![test_outputs](https://user-images.githubusercontent.com/32905878/73545837-1efe4a00-4477-11ea-8459-e05a1f567425.JPG)

**Comment by zxnlee** [comment]
When no maze has been loaded yet:
![image](https://user-images.githubusercontent.com/56616436/73603140-99cf7e00-45b9-11ea-839e-b8b01a896186.png)

After loading maze:
![image](https://user-images.githubusercontent.com/56616436/73603146-b075d500-45b9-11ea-8f01-919543747e15.png)

**Comment by zxnlee** [comment]
View Maze Unit Test Cases Documentation:
[View Maze Unit Test Case.docx](https://github.com/zxnlee/ETIAssignment/files/4154586/View.Maze.Unit.Test.Case.docx)

**Comment by zxnlee** [comment]
feature completed and testing passed.
issue will be closed
@dianizzati @geraldngkj98
