### ISSUE TITLE
Development of "Play maze game"

### ISSUE THREAD

**Issue by zxnlee** [zxnlee/ETIAssignment#6]
Development team to work on the feature "Play maze game".
Details on requirement:
![image](https://user-images.githubusercontent.com/56616436/73123469-4793c900-3fcb-11ea-95be-819525a20177.png)
![image](https://user-images.githubusercontent.com/56616436/73123474-54b0b800-3fcb-11ea-8736-2deac1a26409.png)

Refer to #1 and #2 for test cases.

**Comment by zxnlee** [comment]
@dianizzati Please push back the deadline for this feature by one day (to sunday, 2 feb) as the test cases are not done

**Comment by dianizzati** [comment]
Noted, @kkwwnnpp please take note that the deadline for this feature is extended.

**Comment by kkwwnnpp** [comment]
Noted, thank you.

**Comment by zxnlee** [comment]
@kkwwnnpp @dianizzati test scripts have been committed, please develop the feature

```@geraldngkj98 committed test scripts for 6.0-8.0```

_Originally posted by @zxnlee in https://github.com/zxnlee/ETIAssignment/issues/2#issuecomment-580995038_

**Comment by kkwwnnpp** [comment]
@zxnlee @geraldngkj98 @dianizzati done with development for this feature.

**Comment by zxnlee** [comment]
@geraldngkj98 pls assign for testing

**Comment by kkwwnnpp** [comment]
**Unit Tests:**
**Loading Play Maze**
![LoadingPlayMaze](https://user-images.githubusercontent.com/45195829/73602959-5ffd7800-45b7-11ea-9e80-0e69206cf304.JPG)
**Test Down Key Press**
![testDownKey](https://user-images.githubusercontent.com/45195829/73602961-60960e80-45b7-11ea-9ddc-ef0e80df6668.JPG)
**Test Up Key Press**
![testUpKey](https://user-images.githubusercontent.com/45195829/73602966-612ea500-45b7-11ea-99e7-f52a3e6bc29a.JPG)
**Test Left Key Press**
![testLeftKey](https://user-images.githubusercontent.com/45195829/73602963-60960e80-45b7-11ea-8fcb-130af269570f.JPG)
**Test Right Key Press**
![testRightKey](https://user-images.githubusercontent.com/45195829/73602965-612ea500-45b7-11ea-87a2-bd63d84cf167.JPG)
**Test Invalid Movement**
![testInvalidMovement](https://user-images.githubusercontent.com/45195829/73602962-60960e80-45b7-11ea-95df-429f773f1225.JPG)
**Test Game Completion**
![testCompleteGame](https://user-images.githubusercontent.com/45195829/73602960-5ffd7800-45b7-11ea-997a-23ca6f87a75c.JPG)
**Test Return Main Menu**
![testReturnMainMenuKey](https://user-images.githubusercontent.com/45195829/73602964-612ea500-45b7-11ea-80c1-830be796538a.JPG)
**Test Invalid Input**
![testInvalidInput](https://user-images.githubusercontent.com/45195829/73768873-bb488980-47b4-11ea-9c46-0cc9cc0b69b7.JPG)

**Comment by geraldngkj98** [comment]
@SandyK95 Please start testing on this feature.

**Comment by SandyK95** [comment]
@zxnlee error for test_returnToMainMenuWhilePlayingMaze. please take a look
![test_outputs](https://user-images.githubusercontent.com/32905878/73603479-562b4300-45be-11ea-928e-b5b0f870c6f3.JPG)

**Comment by zxnlee** [comment]
@SandyK95 this test case is not doable as pytest cannot capture output while the program is asking for an input. Updated test case documentation with justifications. Please test again.
@geraldngkj98 pls take note

**Comment by SandyK95** [comment]
@zxnlee @dianizzati @kkwwnnpp @geraldngkj98 testing passed
![test_outputs](https://user-images.githubusercontent.com/32905878/73603607-f6359c00-45bf-11ea-92e4-67a4b05345a6.JPG)

**Comment by kkwwnnpp** [comment]
Play Maze Unit Test Case
[Play Maze Unit Test Case.docx](https://github.com/zxnlee/ETIAssignment/files/4154903/Play.Maze.Unit.Test.Case.docx)

**Comment by zxnlee** [comment]
feature completed and testing passed.
issue will be closed
@dianizzati @geraldngkj98
