### ISSUE TITLE
Development of "Configure current maze"

### ISSUE THREAD

**Issue by zxnlee** [zxnlee/ETIAssignment#7]
Development team to work on the feature "Configure current maze".
Details on requirement:
![image](https://user-images.githubusercontent.com/56616436/73123486-8c1f6480-3fcb-11ea-9b17-334e8b5585ef.png)

Refer to #1 and #2 for test cases.

**Comment by zxnlee** [comment]
@dianizzati test scripts have been committed, please develop the feature
```@zxnlee committed test scripts for the configure maze feature```

_Originally posted by @geraldngkj98 in https://github.com/zxnlee/ETIAssignment/issues/2#issuecomment-581480846_

**Comment by dianizzati** [comment]
@zxnlee Can you finish up on the configure maze feature?

**Comment by zxnlee** [comment]
@dianizzati noted

**Comment by zxnlee** [comment]
@dianizzati done with development
@geraldngkj98 please assign for testing

**Comment by geraldngkj98** [comment]
@SandyK95 Please start the testing for the feature.

**Comment by SandyK95** [comment]
@geraldngkj98 test_viewConfigurationMenu() has failed. please take a look at it.
![test_outputs](https://user-images.githubusercontent.com/32905878/73759633-2f7c3080-47a7-11ea-80d4-06637f8b8ab0.JPG)

**Comment by geraldngkj98** [comment]
@SandyK95 @zxnlee this test case is not doable as pytest cannot capture output while the program is asking for an input. Test case documentation has been updated with justifications. Please proceed with testing again.

**Comment by SandyK95** [comment]
@zxnlee @dianizzati @geraldngkj98 testing done and passed
![test_outputs](https://user-images.githubusercontent.com/32905878/73760764-c72e4e80-47a8-11ea-8956-59bc2a62ffd8.JPG)

**Comment by dianizzati** [comment]
Configure Current Maze
[Configure Current Maze Unit Test Case.docx](https://github.com/zxnlee/ETIAssignment/files/4155260/Configure.Current.Maze.Unit.Test.Case.docx)
 Unit Test Cases Documentation:

**Comment by zxnlee** [comment]
feature completed and testing passed.
issue will be closed
@dianizzati @geraldngkj98
